# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfcc283cc319aa95c71849873cd4db94eae80a3f6af2130364bf8bdd5fbbe2f5fff1f8a464e3e3ec3a339e53485c14c0d7ce36d742d0ac2d6e00ff6f60f4d0b3

test:
  secret_key_base: e09b593959067db9eb5231d5be23c13d100f889b5d5ce2c2b5a0ceea4ef51e402f4eab8de7d469bab9488cd8c5f6c09bea25351b1b77525d7b840f32a14516bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
